name: svg_flutter
description: An upgraded SVG Renderer and widget library for Flutter with error handling capability for Svg Pictures.
repository: https://github.com/IchinoseBinit/svg_flutter
issue_tracker: https://github.com/IchinoseBinit/svg_flutter/issues
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.7
  vector_graphics_codec: ^1.1.7
  vector_graphics_compiler: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: ">=3.7.0-0"